// Generated by scripts/sync-release-info.mjs. Do not edit by hand.
export const RELEASE_INFO = Object.freeze({
  schemaVersion: 1,
  version: '0.3.0',
  channel: 'stable',
  status: 'released',
  changelogPath: 'CHANGELOG.md',
  changelogHeading: '[0.3.0] - 2026-08-30',
  highlights: Object.freeze([
    '建立通用角色、动态职业池、特质点数与透明平衡合同，同时保留 V0.2 兼容投影。',
    '扩展本地规则引擎，统一 D20、状态、特质、装备、金钱、时间、任务与事件的原子硬结果。',
    '引入世界宪法、世界种子、NPC 层级、动态地点、活跃势力、世界导演与多任务图，让世界持续演化而不把事实权交给模型。',
    '统一 AI Provider、内容生成器、生成队列、结构化流式输出、取消、重试和标准错误合同；API Key 继续只保存在系统安全存储。',
    '建立分层记忆、统一上下文、按需世界生成、预取与缓存观测，长期存档不会把完整历史发送给模型。',
    '将存档升级到 V0.3 存档与世界格式，隔离迁移、备份、资源上限、秘密扫描和双实现互操作继续受门禁保护。',
    '视觉系统按设计令牌、基础界面组件、游戏组件、功能页面和旧页面迁移逐层收敛为黑暗奇幻酒馆、跑团手册与现代桌面界面。',
    '完成奇幻、调查、赛博朋克三世界长测和跨世界自由输入压力测试，共复算 104 项行为；伪 Provider 可玩性评分为 8.8/10，置信度中等。',
    '第一轮完整审计重新覆盖架构、安全、规则、SQLite、存档、性能、UI/UX/A11y 与可玩性，并在发布门前逐项关闭发现。',
  ]),
});
