import type { AITask } from './protocol.js';

const world = {
  constitution: {
    schemaVersion: 1,
    worldType: 'Low heroic fantasy',
    era: 'Late medieval sail age',
    technology: 'Late medieval',
    magic: 'Magic always leaves a warm trace.',
    peoples: ['Coastal humans', 'Ash-cliff communities'],
    society: 'Harbor guilds connect isolated settlements',
    politics: 'Local councils negotiate with navigation guilds',
    economy: 'Fishing, coastal trade, and beacon tolls',
    combatScale: 'Personal and small-group conflict',
    deathRules: 'Death is permanent and resurrection does not exist',
    careerRules: 'Careers arise from local guilds, travel, and civic needs',
    equipmentRules: 'Equipment uses available materials and grounded craft',
    npcRules: 'NPC motives follow their knowledge, obligations, and local conditions',
    traitRules: 'Mechanical benefits require balancing drawbacks',
    taboos: [],
  },
  name: 'Ember Coast',
  currentRegion: 'Ash Harbor',
  summary: 'A storm-bound coast linked by old beacon roads.',
  coreConflict: 'The lighthouse fire is fading as an unnatural storm approaches.',
  technologyLevel: 'Late medieval',
  powerRules: ['Magic always leaves a warm trace.'],
  factions: [
    {
      name: 'Lantern Guild',
      description: 'Navigators who maintain the coast beacons.',
      goals: ['Restore the Ash Harbor lighthouse.'],
    },
  ],
  locations: [
    {
      name: 'Ash Harbor',
      description: 'A sheltered port beneath black cliffs.',
      parentName: null,
      factionNames: ['Lantern Guild'],
    },
  ],
  narrativeStyle: 'Grounded heroic fantasy with quiet mysteries.',
  forbiddenElements: [],
  tavernReason: 'Travelers wait here for safe tides and guarded roads.',
  storyHooks: ['The lighthouse flame dims at every moonrise.'],
};
const quest = {
  title: 'The Fading Beacon',
  summary: 'Investigate why the lighthouse fire is failing.',
  objective: 'Restore the beacon before the storm reaches the harbor.',
  failureCost: 'Ships remain trapped beyond the reef.',
};
const factPatch = {
  kind: 'FACT',
  targetId: null,
  rationale: 'The opened chamber becomes a persistent world fact.',
  payload: { statement: 'The old beacon chamber is open.' },
};

export const FAKE_TASK_OUTPUTS = Object.freeze({
  GENERATE_WORLD: world,
  REFINE_WORLD: {
    world,
    changeSummary: ['Clarified the Lantern Guild role while preserving locked rules.'],
  },
  GENERATE_CHARACTER_TRAITS: {
    traits: [
      { name: 'Keen Listener', description: 'Notices quiet changes in people and places.' },
      { name: 'Roadwise', description: 'Reads signs left by travelers and weather.' },
      { name: 'Steady Hands', description: 'Keeps calm while working under pressure.' },
      { name: 'Harborwise', description: 'Understands the customs of ports and sailors.' },
      { name: 'Quiet Courage', description: 'Acts despite fear when others need help.' },
      { name: 'Old Maps', description: 'Recognizes forgotten routes and obsolete landmarks.' },
    ],
  },
  COMPLETE_CHARACTER_BACKGROUND: {
    birthplace: 'The North Road',
    formativeExperience: 'Survived a winter caravan crossing.',
    adventureMotivation: 'Protect travelers from hidden dangers.',
    secret: 'Once followed a false beacon into the marsh.',
    importantPerson: 'A sibling who vanished near Ash Harbor.',
    tavernArrivalReason: 'Seeking the last caravan that saw the missing sibling.',
    initialEquipment: [
      {
        name: 'Weathered Trail Compass',
        description: 'A brass compass marked with old caravan routes.',
      },
      {
        name: 'Waxed Travel Cloak',
        description: 'A salt-stained cloak that turns rain and harbor spray.',
      },
    ],
  },
  GENERATE_QUICK_CHARACTER: {
    name: 'Mira Vale',
    nickname: 'Ember',
    gender: null,
    age: 27,
    identity: 'A world-walking scholar following a compass that remembers lost roads.',
    ancestry: 'Coastal human',
    birthplace: 'Ash Harbor',
    socialClass: 'Guild apprentice',
    faith: null,
    appearance: 'A soot-dark coat, ink-stained fingers, and a brass compass at the belt.',
    personality: 'Curious, measured, and unable to leave a contradiction unexplored.',
    values: ['Truth', 'Safe passage'],
    goals: ['Find the ember road'],
    fears: ['Leading companions onto a false path'],
    secrets: ['The compass answers to her blood'],
    family: ['The Vale household of Ash Harbor'],
    education: ['Harbor Academy cartography'],
    importantPeople: ['Professor Aven'],
    enemies: ['The Ash Cartographer'],
    experiences: ['Survived a skyquake while mapping the north road'],
    career: {
      id: 'career-lantern-warden',
      displayName: 'Lantern Warden',
      legacyArchetype: 'WARRIOR',
    },
    attributePriority: ['knowledge', 'agility', 'charisma', 'physique'],
    proficiencies: ['Cartography'],
    abilities: ['Read the road'],
    languages: ['Common'],
    traits: [
      { name: 'Observant', description: 'Notices small inconsistencies.' },
      { name: 'Restless', description: 'Cannot leave a mystery alone.' },
    ],
    legacyBackground: {
      birthplace: 'Ash Harbor',
      formativeExperience: 'Survived a skyquake while mapping the north road.',
      adventureMotivation: 'Find the ember road before another traveler disappears.',
      secret: 'The compass answers to her blood.',
      importantPerson: 'Professor Aven',
      tavernArrivalReason: 'The compass points beneath Ember Rest.',
    },
    extensions: [],
  },
  EDIT_CHARACTER_DRAFT: {
    kind: 'DRAFT_PATCH',
    updates: [{ path: 'identity', value: 'A patient investigator of ember-lit roads.' }],
  },
  GENERATE_CAREER_POOL: {
    schemaVersion: 1,
    careers: [
      {
        id: 'career-lantern-warden',
        name: 'Lantern Warden',
        rarity: 'COMMON',
        role: 'Maintains beacon roads and escorts travelers through storm-dark passes.',
        skills: ['Route keeping', 'Weather signs'],
        equipmentTags: ['Beacon lantern', 'Waxed cloak'],
        socialPosition: 'Licensed civic guild member',
        relationshipHooks: ['Answers to the Lantern Guild'],
        risks: ['Must respond when a beacon fails'],
        requirements: ['Guild apprenticeship'],
        constitutionEvidence: {
          careerRules: 'Careers arise from local guilds, travel, and civic needs',
          society: 'Harbor guilds connect isolated settlements',
          technology: 'Late medieval',
          economy: 'Fishing, coastal trade, and beacon tolls',
        },
        legacyArchetype: 'WARRIOR',
      },
      {
        id: 'career-shoal-pilot',
        name: 'Shoal Pilot',
        rarity: 'UNCOMMON',
        role: 'Guides vessels through reefs and changing coastal channels.',
        skills: ['Navigation', 'Tide reading'],
        equipmentTags: ['Charts', 'Sounding line'],
        socialPosition: 'Licensed navigation specialist',
        relationshipHooks: ['Owes the harbor council'],
        risks: ['Blamed for every grounded ship'],
        requirements: ['Guild sponsorship'],
        constitutionEvidence: {
          careerRules: 'Careers arise from local guilds, travel, and civic needs',
          society: 'Harbor guilds connect isolated settlements',
          technology: 'Late medieval',
          economy: 'Fishing, coastal trade, and beacon tolls',
        },
        legacyArchetype: 'SCHOLAR',
      },
      {
        id: 'career-storm-reader',
        name: 'Storm Reader',
        rarity: 'RARE',
        role: 'Interprets dangerous weather and the warm traces left by ritual magic.',
        skills: ['Weather signs', 'Ritual observation'],
        equipmentTags: ['Barometer', 'Trace journal'],
        socialPosition: 'Rare consultant to captains and councils',
        relationshipHooks: ['Rival of the Lantern Guild augur'],
        risks: ['A failed warning can ruin a settlement'],
        requirements: ['Survive a guild-observed great storm'],
        constitutionEvidence: {
          careerRules: 'Careers arise from local guilds, travel, and civic needs',
          society: 'Harbor guilds connect isolated settlements',
          technology: 'Late medieval',
          economy: 'Fishing, coastal trade, and beacon tolls',
        },
        legacyArchetype: 'SCHOLAR',
      },
      {
        id: 'career-council-envoy',
        name: 'Council Envoy',
        rarity: 'SPECIAL',
        role: 'Carries binding negotiations between isolated harbor councils.',
        skills: ['Negotiation', 'Civic protocol'],
        equipmentTags: ['Sealed charter'],
        socialPosition: 'Temporary voice of a harbor council',
        relationshipHooks: ['Bound to a council faction'],
        risks: ['Held responsible for a broken accord'],
        requirements: ['Named by a sitting council'],
        constitutionEvidence: {
          careerRules: 'Careers arise from local guilds, travel, and civic needs',
          society: 'Harbor guilds connect isolated settlements',
          technology: 'Late medieval',
          economy: 'Fishing, coastal trade, and beacon tolls',
        },
        legacyArchetype: 'DIPLOMAT',
      },
    ],
  },
  GENERATE_ITEMS: {
    schemaVersion: 1,
    items: [
      {
        id: 'item-stormglass-compass',
        name: 'Stormglass Compass',
        description: 'A weathered compass whose clouded face clears near old beacon roads.',
        category: 'TOOL',
        appearance: 'Dark brass surrounds a pane of blue-gray stormglass.',
        history: 'A route warden carried it before the harbor beacons went dark.',
        origin: 'The old lantern guild workshops.',
        narrativeAbilities: ['Reveals faded route marks when held beneath beacon light'],
        semanticEffects: ['Recognized by surviving lantern wardens'],
        balanceTags: ['QUEST_REWARD', 'NON_COMBAT'],
        bindings: [
          {
            kind: 'QUEST',
            targetId: 'quest-beacon',
            trigger: 'QUEST_CONTEXT',
            summary: 'Recovered while restoring the lost beacon.',
          },
          {
            kind: 'NPC',
            targetId: 'npc-owner',
            trigger: 'NPC_RECOGNITION',
            summary: 'The tavern owner recognizes the old guild workmanship.',
          },
        ],
        constitutionEvidence: {
          equipmentRules: 'Equipment remains grounded and scarce',
          technology: 'Late medieval',
          economy: 'Fishing, coastal trade, and beacon tolls',
        },
      },
    ],
  },
  GENERATE_NPC_LOD: {
    schemaVersion: 1,
    npc: {
      npcId: 'npc-background-1',
      lod: 1,
      identityAnchor: 'anchor-background-1',
      populationRole: 'Harbor passerby',
      name: 'Nera Fen',
      appearance: 'A rain-dark cloak and a coil of pale rope.',
      currentBehavior: 'Studies the tide marks beside the tavern door.',
      career: null,
      personality: null,
      goals: [],
      knowledgeFactIds: [],
      relationshipNpcIds: [],
      memoryIds: [],
      secretFactIds: [],
      questIds: [],
      itemIds: [],
      experienceEventIds: [],
      constitutionEvidence: {
        npcRules: 'NPC motives follow knowledge and obligations',
        society: 'Harbor guilds connect isolated settlements',
        technology: 'Late medieval',
      },
    },
  },
  GENERATE_LOCATIONS: {
    schemaVersion: 1,
    locations: [
      {
        id: 'location-cinder-market',
        name: 'Cinder Market',
        kind: 'DISTRICT',
        parentLocationId: 'location-ash-harbor',
        description: 'A covered market pressed between the seawall and old ropewalks.',
        atmosphere: 'Salt-damp, crowded, and alert to every arriving ship.',
        features: ['Bell-marked exchange hall'],
        factionIds: [],
        connections: ['location-ash-harbor'],
        currentSituation: 'Merchants are withholding charts after a beacon failure.',
        constitutionEvidence: {
          technology: 'Late medieval',
          magic: 'Magic always leaves a warm trace.',
          society: 'Harbor guilds connect isolated settlements',
          politics: 'Local councils negotiate with navigation guilds',
        },
      },
    ],
  },
  GENERATE_FACTIONS: {
    schemaVersion: 1,
    factions: [
      {
        id: 'faction-lantern',
        name: 'Lantern Guild',
        goal: 'Restore the Ash Harbor lighthouse.',
        resources: ['Harbor patrols', 'Beacon stores'],
        leadership: ['The Lantern Council'],
        enemyFactionIds: [],
        allyFactionIds: [],
        territoryLocationIds: ['location-ash-harbor'],
        currentAction: 'Reopen the northern beacon road.',
        playerRelation: 'UNKNOWN',
        constitutionEvidence: {
          technology: 'Late medieval',
          society: 'Harbor guilds connect isolated settlements',
          politics: 'Local councils negotiate with navigation guilds',
          economy: 'Fishing, coastal trade, and beacon tolls',
        },
      },
    ],
  },
  GENERATE_TAVERN: {
    name: 'Ember Rest',
    position: 'The harbor crossroads',
    environment: 'A warm stone hall filled with salt air and amber light.',
    specialRules: ['Weapons remain sheathed beside the common fire.'],
    longTermProblem: 'A strange light appears beneath the cellar each night.',
    owner: {
      name: 'Ilyra Venn',
      identity: 'Innkeeper and retired route warden',
      appearance: 'Tall, with a weathered red wool coat.',
      personality: 'Practical, observant, and slow to trust.',
      goal: 'Keep the harbor road open.',
      secret: 'Knows a sealed tunnel reaches toward the lighthouse.',
      speechStyle: 'Measured statements and pointed questions.',
      currentMood: 'Concerned',
    },
  },
  GENERATE_NPCS: {
    npcs: [
      {
        residency: 'RESIDENT',
        name: 'Tomas Reed',
        identity: 'Cartographer',
        appearance: 'Ink-stained hands and a patched blue scarf.',
        personality: 'Patient and skeptical.',
        goal: 'Map the sealed coastal tunnels.',
        secret: 'Has already entered the first tunnel chamber.',
        speechStyle: 'Careful questions followed by precise corrections.',
        currentMood: 'Curious',
        visitReason: null,
      },
      {
        residency: 'RESIDENT',
        name: 'Nessa Vale',
        identity: 'Harbor herbalist',
        appearance: 'A green coat hung with small labeled pouches.',
        personality: 'Warm, direct, and difficult to surprise.',
        goal: 'Learn why marsh plants are blooming out of season.',
        secret: 'Keeps a sample that glows with the same light as the cellar.',
        speechStyle: 'Short practical advice followed by dry humor.',
        currentMood: 'Watchful',
        visitReason: null,
      },
      {
        residency: 'TEMPORARY_VISITOR',
        name: 'Sera Holt',
        identity: 'Storm courier',
        appearance: 'Travel cloak crusted with sea salt.',
        personality: 'Restless but generous.',
        goal: 'Deliver a warning to the Lantern Guild.',
        secret: 'Lost the original warning seal.',
        speechStyle: 'Quick sentences and nautical idioms.',
        currentMood: 'Urgent',
        visitReason: 'Waiting for the causeway to reopen.',
      },
    ],
    rumors: [
      {
        statement: 'A warm light moves beneath the old cellar after midnight.',
        sourceNpcName: 'Tomas Reed',
        sourceBasis: 'WITNESS',
        confidence: 0.9,
        veracity: 'TRUE',
      },
      {
        statement: 'The Lantern Guild pays in silver for maps of the sealed tunnels.',
        sourceNpcName: 'Nessa Vale',
        sourceBasis: 'FACTION_MESSAGE',
        confidence: 0.6,
        veracity: 'PARTIAL',
      },
      {
        statement: 'The storm courier crossed the flooded causeway alone.',
        sourceNpcName: 'Sera Holt',
        sourceBasis: 'HEARSAY',
        confidence: 0.4,
        veracity: 'UNKNOWN',
      },
    ],
  },
  NPC_REPLY: {
    reply: 'I will show you the cellar door, but stay close and touch nothing warm.',
    mood: 'Wary',
    suggestedTopics: ['The old tunnel', 'The lighthouse keeper', 'The cellar door'],
    memoryCandidate: 'The player asked Ilyra to reveal the cellar door.',
    relationshipProposal: { trust: 1 },
  },
  GENERATE_DIALOGUE_SUGGESTIONS: {
    suggestions: [
      { text: '询问旧隧道最近的动静', addressedNpcId: 'npc-owner' },
      { text: '谈谈灯塔守望者留下的线索', addressedNpcId: 'npc-owner' },
      { text: '观察炉边众人对地窖门的反应', addressedNpcId: null },
    ],
  },
  PROPOSE_TAVERN_SCENE_ACTION: {
    actorId: 'npc-owner',
    action: 'SPEAK',
    targetNpcId: null,
    utterance: 'The lantern road has been too quiet tonight.',
    citedKnowledgeIds: [],
    urgency: 1,
    rationale: 'The player addressed the room and the owner has a relevant concern.',
  },
  GENERATE_QUEST: {
    content: quest,
    risk: 'MODERATE',
    recommendedAttributes: ['knowledge', 'agility'],
    expectedTurns: { min: 8, max: 12 },
    rewardTier: 'NOTABLE',
    relatedNpcIds: [],
    relatedFactIds: [],
  },
  GENERATE_ADVENTURE_PLAN: {
    objective: quest.objective,
    risk: 'MODERATE',
    expectedTurns: { min: 8, max: 12 },
    coreScenes: ['Open the cellar passage.', 'Cross the flooded causeway.', 'Reach the beacon.'],
    necessaryClues: [
      {
        title: 'Scorched Lens',
        description: 'The beacon lens was burned from inside.',
        isCore: true,
      },
      {
        title: 'Tide Ledger',
        description: 'The flooding follows a deliberate release schedule.',
        isCore: true,
      },
      {
        title: 'Keeper Signet',
        description: 'The missing keeper sealed the lower chamber personally.',
        isCore: true,
      },
    ],
    majorObstacles: ['A rusted lock.', 'A flooded tunnel.', 'The approaching storm.'],
    possibleEndings: ['The beacon is restored.', 'The harbor evacuates before the storm.'],
    failureCost: quest.failureCost,
  },
  GENERATE_ADVENTURE_TURN: {
    sceneText: 'Warm light leaks through the old cellar lock as the storm shakes the shutters.',
    speakerNpcIds: [],
    suggestedActions: [
      { text: 'Study the lock.' },
      { text: 'Ask Ilyra for the old key.' },
      { text: 'Observe the warm marks around the frame.' },
    ],
    checkRequest: {
      attribute: 'knowledge',
      difficulty: 11,
      reason: 'Identify the hidden locking mechanism.',
    },
    discoveredClues: ['Scorched Lens'],
    statePatchProposals: [factPatch],
    adventureState: 'CHECK_REQUIRED',
  },
  RESOLVE_DICE_RESULT: {
    narration: 'The hidden catch yields, revealing a narrow stair lit by ember-colored moss.',
    consequence: 'The cellar passage can now be entered safely.',
    statePatchProposals: [factPatch],
  },
  GENERATE_WORLD_EVENT: {
    title: 'The tide turns',
    description: 'The storm front moves closer and floods the outer harbor road.',
    newFacts: ['The outer harbor road is flooded.'],
    clockAdvances: [
      { clockId: 'clock-storm', amount: 1, reason: 'Another storm tide has arrived.' },
    ],
  },
  SUMMARIZE_ADVENTURE: {
    summary: 'The party opened the cellar passage and found a route toward the lighthouse.',
    keyDecisions: ['Trusted Ilyra.', 'Opened the cellar door.'],
    unresolvedThreads: ['Who damaged the beacon lens?'],
    nextDirections: ['Ask the Lantern Guild who last serviced the lens.'],
    npcUpdates: [
      {
        npcId: 'npc-owner',
        currentMood: 'Relieved',
        relationshipPatch: { trust: 1 },
      },
    ],
    tavernChange: {
      kind: 'TROPHY',
      description: 'A scorched shard of the restored beacon lens hangs above the hearth.',
    },
    statePatchProposals: [
      {
        kind: 'QUEST',
        targetId: 'quest-beacon',
        rationale: 'The beacon objective was completed.',
        payload: { status: 'COMPLETED' },
      },
      {
        kind: 'RELATIONSHIP',
        targetId: 'npc-owner',
        rationale: 'Ilyra trusts the player after the beacon rescue.',
        payload: { trust: 1 },
      },
      {
        kind: 'ITEM_REWARD',
        targetId: null,
        rationale: 'The completed quest grants its authorized reward.',
        payload: {
          questId: 'quest-beacon',
          name: 'Stormglass Compass',
          description: 'A brass compass fitted with a sliver of stormglass.',
          rewardTier: 'NOTABLE',
        },
      },
    ],
  },
  EXTRACT_MEMORIES: {
    memories: [
      {
        summary: 'The player promised Ilyra to investigate the lighthouse passage.',
        sourceTurnIds: ['turn-1'],
      },
    ],
  },
  CHECK_CONSISTENCY: {
    consistent: true,
    issues: [],
  },
  COMBAT_CONTENT_GENERATION: {
    schemaVersion: 1,
    authority: 'UNTRUSTED_CONCEPT',
    concept: {
      theme: '雷法',
      role: '爆发与轻度控制',
      flavor: '引动雷息震慑敌人的修仙术法。',
      mechanicalIntent: ['高伤害', '高灵力消耗', '小概率造成神识紊乱'],
      candidateTags: ['spell', 'lightning', 'control'],
      targetIntent: '选择单个敌人',
      rarityIntent: '稀有',
      levelIntent: '中期成长阶段',
    },
  },
} satisfies Readonly<Record<AITask, unknown>>);
